services:
  app:
    image: php:8.1-fpm
    container_name: symfony_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - /etc/ssl/certs:/etc/ssl/certs:ro 
    working_dir: /var/www/html
    networks:
      - symfony_network
  
  web:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony_network

volumes:
  db_data:

networks:
  symfony_network:
    driver: bridge
